image: golang:1.11.2

variables:
  REPO_NAME: gitlab.corp.local/knuth/lemonade

stages:
  - test
  - Build Image
  - Deploy to K8s

  
format:
    stage: test
    tags:
      - shared-runner
    script:
      - mkdir -p $GOPATH/src/$REPO_NAME
      - cp -r $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
      - cd $GOPATH/src/$REPO_NAME
      - go get github.com/lib/pq
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet -composites=false $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)


Kaniko:
  stage: Build Image
  tags:
    - shared-runner
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - master

#Deploy:
#  stage: Deploy to K8s
#  tags:
#    - shared-runner
#  image: 
#    name: wernight/kubectl
#    entrypoint: [""]
#  script:
#    - kubectl version