apiVersion: v1
kind: Service
metadata:
  name: lemonade-service
spec:
  selector:
    app: lemonade
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemonade-deployment
  labels:
    app: lemonade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lemonade
  template:
    metadata:
      labels:
        app: lemonade
    spec:
      containers:
      - name: lemonade
        image: vknuth/knuth-repo:lemonade
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: knuth